services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: buybye
      POSTGRES_PASSWORD: buybye
      POSTGRES_DB: buybye
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "3000:3000"
    env_file: .env
    environment:
      WATCHPACK_POLLING: "true"
    depends_on:
      - db
# For Ulysse: remove these  and launch with
# Powershell, for Rawan: you can keep them.
# (start) lines to remove
    volumes:
      - .:/app
      - /app/node_modules
# (end) lines to remove


volumes:
  pgdata:
